const products = [
  {
    id: 1,
    name: "Cable Management Kit",
    nameAr: "طقم تنظيم الكابلات",
    slug: "cable-management-kit",
    description: "315-piece adhesive cable organizer",
    descriptionAr: "منظم كابلات لاصق من 315 قطعة",
    price: 65,
    category: "Workspace",
    featured: false,
    image: "📦",
    images: ["📦"]
  },
  {
    id: 2,
    name: "Wireless Charging Stand",
    nameAr: "حامل شحن لاسلكي",
    slug: "wireless-charging-stand",
    description: "Fast Qi charging stand",
    descriptionAr: "حامل شحن سريع Qi",
    price: 120,
    category: "Phone Accessories",
    featured: true,
    image: "📱",
    images: ["📱"]
  },
  {
    id: 3,
    name: "LED Strip Lights",
    nameAr: "أضواء LED الشريطية",
    slug: "led-strip-lights",
    description: "RGB smart LED strip (5m)",
    descriptionAr: "شريط LED ذكي RGB (5 متر)",
    price: 95,
    category: "Home",
    featured: false,
    image: "💡",
    images: ["💡"]
  },
  {
    id: 4,
    name: "Laptop Stand",
    nameAr: "حامل لابتوب",
    slug: "laptop-stand",
    description: "Adjustable aluminum stand",
    descriptionAr: "حامل ألمنيوم قابل للتعديل",
    price: 110,
    category: "Workspace",
    featured: false,
    image: "💻",
    images: ["💻"]
  },
  {
    id: 5,
    name: "Phone Car Mount",
    nameAr: "حامل هاتف للسيارة",
    slug: "phone-car-mount",
    description: "360° magnetic car holder",
    descriptionAr: "حامل مغناطيسي 360 درجة",
    price: 45,
    category: "Car Accessories",
    featured: false,
    image: "🚗",
    images: ["🚗"]
  },
  {
    id: 6,
    name: "Desk Organizer",
    nameAr: "منظم مكتب",
    slug: "desk-organizer",
    description: "Multi-compartment desk caddy",
    descriptionAr: "منظم مكتب متعدد الأقسام",
    price: 85,
    category: "Workspace",
    featured: true,
    image: "📝",
    images: ["📝"]
  },
  {
    id: 7,
    name: "Smart Plug",
    nameAr: "مقبس ذكي",
    slug: "smart-plug",
    description: "WiFi-enabled smart socket",
    descriptionAr: "مقبس ذكي بخاصية WiFi",
    price: 55,
    category: "Home",
    featured: true,
    image: "🔌",
    images: ["🔌"]
  },
  {
    id: 8,
    name: "USB Hub",
    nameAr: "موزع USB",
    slug: "usb-hub",
    description: "7-port USB 3.0 hub",
    descriptionAr: "موزع USB 3.0 بـ 7 منافذ",
    price: 75,
    category: "Workspace",
    featured: false,
    image: "🔗",
    images: ["🔗"]
  },
  {
    id: 9,
    name: "Product 9",
    nameAr: "منتج 9",
    slug: "product-9",
    description: "Placeholder product 9",
    descriptionAr: "منتج تجريبي 9",
    price: 100,
    category: "Home",
    featured: false,
    image: "🎁",
    images: ["🎁"]
  },
  {
    id: 10,
    name: "Product 10",
    nameAr: "منتج 10",
    slug: "product-10",
    description: "Placeholder product 10",
    descriptionAr: "منتج تجريبي 10",
    price: 90,
    category: "Workspace",
    featured: false,
    image: "🎉",
    images: ["🎉"]
  }
];

const categoryTranslations = {
  "All Products": "جميع المنتجات",
  "Workspace": "مساحة العمل",
  "Phone Accessories": "إكسسوارات الهاتف",
  "Home": "المنزل",
  "Car Accessories": "إكسسوارات السيارة"
};
